"""
PyMOL script generation for AlphaFold2-predicted protein-protein complexes.

Generates .pml command files that load a PDB structure and apply layered
visualisation: chain colouring, pLDDT confidence colouring, interface residue
highlighting, and (optionally) variant position colouring by structural context.

Architecture:
    - Pure string generators (no I/O) produce each visualisation layer
    - build_pymol_script() assembles layers into a complete .pml file
    - extract_interface_data() re-reads a PDB to get interface residue numbers
    - generate_pymol_scripts_for_results() is the toolkit.py entry point
    - Optional py3Dmol fallback for in-notebook rendering

Data sources:
    - PDB files from AlphaFold2 predictions (pLDDT in B-factor column)
    - Interface data via pdockq.read_pdb_with_chain_info_New / find_best_chain_pair_New
    - Variant details from variant_mapper.format_variant_details() output

Usage (standalone):
    python pymol_scripts.py generate --pdb complex.pdb
    python pymol_scripts.py generate --pdb complex.pdb --output pymol_output/ --render
    python pymol_scripts.py batch --csv results.csv --pdb-dir D:\\ProteinComplexes

Usage (via toolkit.py):
    python toolkit.py --dir DIR --output results.csv --interface --pae --pymol
    python toolkit.py --dir DIR --output results.csv --interface --pae --enrich ALIASES --variants --pymol --pymol-render
"""

import argparse
import csv
import os
import re
import sys
from pathlib import Path
from typing import Optional, Union

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


# ── Constants ────────────────────────────────────────────────────────

DEFAULT_PYMOL_OUTPUT_DIR = "pymol_scripts"

# PyMOL colour names per chain (supports up to 10 chains)
CHAIN_COLOURS = {
    'A': 'marine',
    'B': 'salmon',
    'C': 'forest',
    'D': 'wheat',
    'E': 'slate',
    'F': 'lightorange',
    'G': 'palegreen',
    'H': 'lightpink',
    'I': 'palecyan',
    'J': 'lightteal',
}

# Canonical AlphaFold2 pLDDT colour scheme (Jumper et al. 2021)
# Each entry: (label, b_factor_condition, hex_colour)
PLDDT_COLOUR_BANDS = [
    ('plddt_vhigh', 'b > 90',             '0x0053D6'),   # Very high (blue)
    ('plddt_high',  'b > 70 and b <= 90',  '0x65CBF3'),   # Confident (cyan)
    ('plddt_low',   'b > 50 and b <= 70',  '0xFFDB13'),   # Low (yellow)
    ('plddt_vlow',  'b <= 50',             '0xFF7D45'),   # Very low (orange)
]

# Interface residue colour
INTERFACE_COLOUR = 'hotpink'

# Variant structural context colours (matches variant_mapper.py classification)
VARIANT_CONTEXT_COLOURS = {
    'interface_core':        'red',
    'interface_rim':         'orange',
    'surface_non_interface': 'yellow',
    'buried_core':           'gray70',
}

# Default fallback colour for unknown variant context
VARIANT_DEFAULT_COLOUR = 'white'

# Rendering defaults
DEFAULT_RAY_WIDTH = 2400
DEFAULT_RAY_HEIGHT = 1800
DEFAULT_DPI = 300

# Regex for parsing variant detail strings from variant_mapper.format_variant_details()
# Format: REF{POS}ALT:context:clinical_significance
# Example: K81P:interface_core:pathogenic
_VARIANT_DETAIL_RE = re.compile(
    r'^([A-Z*?])(\d+)([A-Z*?]):([^:]+):(.*)$'
)

# py3Dmol optional import
try:
    import py3Dmol
    _HAS_PY3DMOL = True
except ImportError:
    _HAS_PY3DMOL = False


# ── PML Command Generators ──────────────────────────────────────────

def generate_pml_header(pdb_path: str, complex_name: str) -> str:
    """Generate the header section of a .pml script.

    Loads the PDB, sets basic display and background.

    Args:
        pdb_path: Absolute or relative path to the PDB file.
        complex_name: Identifier used as the PyMOL object name.

    Returns:
        Multi-line string with load, display, and background commands.
    """
    # Normalise path separators to forward slashes (PyMOL convention)
    pdb_path_clean = str(pdb_path).replace('\\', '/')
    return (
        f"# === PyMOL Script for {complex_name} ===\n"
        f"# Generated by protein-complexes-toolkit\n"
        f"\n"
        f"# -- Load structure --\n"
        f"load {pdb_path_clean}, {complex_name}\n"
        f"hide everything\n"
        f"show cartoon\n"
        f"bg_color white\n"
    )


def generate_chain_colouring(chain_a: str, chain_b: str) -> str:
    """Generate chain colouring commands.

    Args:
        chain_a: First chain identifier.
        chain_b: Second chain identifier.

    Returns:
        Multi-line string with chain colour commands.
    """
    colour_a = CHAIN_COLOURS.get(chain_a, 'marine')
    colour_b = CHAIN_COLOURS.get(chain_b, 'salmon')
    return (
        f"\n# -- Chain colouring --\n"
        f"color {colour_a}, chain {chain_a}\n"
        f"color {colour_b}, chain {chain_b}\n"
    )


def generate_plddt_colouring() -> str:
    """Generate pLDDT confidence colouring commands.

    Uses the canonical AlphaFold2 4-band colour scheme based on B-factor
    values (which store pLDDT in AlphaFold PDB files).

    Returns:
        Multi-line string with selection and colour commands.
    """
    lines = ["\n# -- pLDDT colouring (B-factor) --"]
    for label, condition, hex_colour in PLDDT_COLOUR_BANDS:
        lines.append(f"select {label}, {condition}")
        lines.append(f"color {hex_colour}, {label}")
    lines.append("deselect")
    return '\n'.join(lines) + '\n'


def generate_interface_highlighting(
    chain_a: str,
    chain_b: str,
    interface_resi_a: list[int],
    interface_resi_b: list[int],
) -> str:
    """Generate interface residue highlighting commands.

    Shows interface residues as sticks coloured in hotpink.

    Args:
        chain_a: First chain identifier.
        chain_b: Second chain identifier.
        interface_resi_a: PDB residue numbers at the interface on chain A.
        interface_resi_b: PDB residue numbers at the interface on chain B.

    Returns:
        Multi-line string with selection, representation, and colour commands.
        Empty string if both lists are empty.
    """
    if not interface_resi_a and not interface_resi_b:
        return ''

    lines = ["\n# -- Interface residues --"]

    if interface_resi_a:
        resi_str = '+'.join(str(r) for r in sorted(interface_resi_a))
        lines.append(f"select interface_a, chain {chain_a} and resi {resi_str}")

    if interface_resi_b:
        resi_str = '+'.join(str(r) for r in sorted(interface_resi_b))
        lines.append(f"select interface_b, chain {chain_b} and resi {resi_str}")

    # Show and colour
    sel_parts = []
    if interface_resi_a:
        sel_parts.append('interface_a')
    if interface_resi_b:
        sel_parts.append('interface_b')
    sel_combined = ' or '.join(sel_parts)

    lines.append(f"show sticks, {sel_combined}")
    lines.append(f"color {INTERFACE_COLOUR}, {sel_combined}")
    lines.append("deselect")

    return '\n'.join(lines) + '\n'


def generate_variant_highlighting(
    chain_a: str,
    chain_b: str,
    variant_records_a: Optional[list[dict]] = None,
    variant_records_b: Optional[list[dict]] = None,
) -> str:
    """Generate variant position highlighting commands.

    Shows variant positions as spheres coloured by structural context.

    Args:
        chain_a: First chain identifier.
        chain_b: Second chain identifier.
        variant_records_a: Parsed variant dicts for chain A
            (keys: position, context). None to skip.
        variant_records_b: Parsed variant dicts for chain B. None to skip.

    Returns:
        Multi-line string with selection, representation, and colour commands.
        Empty string if no variants provided.
    """
    all_variants = []
    if variant_records_a:
        for v in variant_records_a:
            all_variants.append((chain_a, v))
    if variant_records_b:
        for v in variant_records_b:
            all_variants.append((chain_b, v))

    if not all_variants:
        return ''

    # Group variants by (chain, context) for efficient selection
    groups: dict[tuple[str, str], list[int]] = {}
    for chain, var in all_variants:
        ctx = var.get('context', 'unknown')
        key = (chain, ctx)
        if key not in groups:
            groups[key] = []
        pos = var.get('position')
        if pos is not None:
            groups[key].append(int(pos))

    if not groups:
        return ''

    lines = ["\n# -- Variant positions --"]
    sel_names = []

    for (chain, ctx), positions in sorted(groups.items()):
        if not positions:
            continue
        # Create a unique selection name
        safe_ctx = ctx.replace(' ', '_')
        sel_name = f"var_{safe_ctx}_{chain}"
        resi_str = '+'.join(str(r) for r in sorted(set(positions)))
        colour = VARIANT_CONTEXT_COLOURS.get(ctx, VARIANT_DEFAULT_COLOUR)

        lines.append(f"select {sel_name}, chain {chain} and resi {resi_str}")
        lines.append(f"show spheres, {sel_name}")
        lines.append(f"color {colour}, {sel_name}")
        sel_names.append(sel_name)

    if sel_names:
        lines.append("deselect")

    return '\n'.join(lines) + '\n'


def generate_rendering_commands(
    output_png_path: Optional[str] = None,
    render: bool = False,
) -> str:
    """Generate camera orientation and optional rendering commands.

    Args:
        output_png_path: Path for PNG output file. Used only when render=True.
        render: If True, include ray-tracing and PNG save commands (uncommented).
            If False, include them as comments for manual use.

    Returns:
        Multi-line string with camera and rendering commands.
    """
    lines = [
        "\n# -- Camera and rendering --",
        "orient",
        "zoom complete=1",
        "set ray_opaque_background, 1",
    ]

    prefix = '' if render else '# '
    lines.append(f"{prefix}ray {DEFAULT_RAY_WIDTH}, {DEFAULT_RAY_HEIGHT}")

    if output_png_path:
        png_path = str(output_png_path).replace('\\', '/')
        lines.append(f"{prefix}png {png_path}, dpi={DEFAULT_DPI}")
    else:
        lines.append(f"{prefix}png output.png, dpi={DEFAULT_DPI}")

    return '\n'.join(lines) + '\n'


# ── Script Assembly ──────────────────────────────────────────────────

def build_pymol_script(
    pdb_path: str,
    complex_name: str,
    chain_a: str,
    chain_b: str,
    interface_resi_a: list[int],
    interface_resi_b: list[int],
    variant_records_a: Optional[list[dict]] = None,
    variant_records_b: Optional[list[dict]] = None,
    render_png: bool = False,
    output_png_path: Optional[str] = None,
) -> str:
    """Assemble a complete PyMOL .pml script from individual layers.

    Combines header, chain colouring, pLDDT colouring, interface highlighting,
    optional variant highlighting, and rendering commands into a single script.

    Args:
        pdb_path: Path to the PDB file.
        complex_name: Complex identifier (used as PyMOL object name).
        chain_a: First chain identifier.
        chain_b: Second chain identifier.
        interface_resi_a: PDB residue numbers at interface on chain A.
        interface_resi_b: PDB residue numbers at interface on chain B.
        variant_records_a: Parsed variant dicts for chain A. None to skip.
        variant_records_b: Parsed variant dicts for chain B. None to skip.
        render_png: If True, uncomment ray/png commands for batch rendering.
        output_png_path: Custom PNG output path. None uses default.

    Returns:
        Complete .pml script as a string.
    """
    sections = [
        generate_pml_header(pdb_path, complex_name),
        generate_chain_colouring(chain_a, chain_b),
        generate_plddt_colouring(),
        generate_interface_highlighting(chain_a, chain_b,
                                        interface_resi_a, interface_resi_b),
        generate_variant_highlighting(chain_a, chain_b,
                                      variant_records_a, variant_records_b),
        generate_rendering_commands(output_png_path, render=render_png),
    ]
    return ''.join(sections)


# ── Variant Detail Parsing ───────────────────────────────────────────

def parse_variant_details_for_pymol(details_str: str) -> list[dict]:
    """Parse a pipe-separated variant details string into dicts for PyMOL.

    Extracts position and structural context from the format produced by
    variant_mapper.format_variant_details():
        REF{POS}ALT:context:clinical_significance

    Args:
        details_str: Pipe-separated variant string, e.g.
            'K81P:interface_core:pathogenic|E82K:interface_rim:VUS'.

    Returns:
        List of dicts with keys: ref, position (int), alt, context, clinical.
        Malformed entries are silently skipped.
    """
    if not details_str or details_str == '-':
        return []

    records = []
    for part in details_str.split('|'):
        part = part.strip()
        if not part or part.startswith('...'):
            continue

        match = _VARIANT_DETAIL_RE.match(part)
        if match:
            records.append({
                'ref': match.group(1),
                'position': int(match.group(2)),
                'alt': match.group(3),
                'context': match.group(4),
                'clinical': match.group(5),
            })

    return records


# ── Interface Residue Extraction ─────────────────────────────────────

def extract_interface_data(pdb_path: Union[str, Path]) -> dict:
    """Re-read a PDB file and extract interface residue PDB numbers.

    Uses pdockq imports to load chain info and find the best interacting
    chain pair, then converts interface residue indices to PDB residue numbers.

    Args:
        pdb_path: Path to an AlphaFold2 PDB file.

    Returns:
        Dict with keys: chain_a, chain_b, interface_resi_a (list[int]),
        interface_resi_b (list[int]).

    Raises:
        FileNotFoundError: If PDB file does not exist.
        RuntimeError: If pdockq import or chain pair detection fails.
    """
    from pdockq import (
        read_pdb_with_chain_info_New as read_pdb_with_chain_info,
        find_best_chain_pair_New as find_best_chain_pair,
    )

    pdb_path = Path(pdb_path)
    if not pdb_path.exists():
        raise FileNotFoundError(f"PDB file not found: {pdb_path}")

    chain_info = read_pdb_with_chain_info(str(pdb_path))
    ch_a, ch_b, contact = find_best_chain_pair(chain_info, t=8)

    interface_resi_a = [
        chain_info.chain_res_numbers[ch_a][i]
        for i in sorted(contact.interface_residues_a)
    ]
    interface_resi_b = [
        chain_info.chain_res_numbers[ch_b][i]
        for i in sorted(contact.interface_residues_b)
    ]

    return {
        'chain_a': ch_a,
        'chain_b': ch_b,
        'interface_resi_a': interface_resi_a,
        'interface_resi_b': interface_resi_b,
    }


# ── PDB File Discovery ────────────────────────────────────────────

def _build_pdb_lookup(pdb_dir: Path) -> dict[str, Path]:
    """Scan a directory and map cleaned complex names to PDB file paths.

    Reuses ``toolkit.parse_complex_name()`` to strip AlphaFold2 filename
    suffixes (e.g. ``_relaxed_model_1_multimer_v3_pred_0``) — exactly the
    same logic that the main pipeline uses to derive ``complex_name`` in
    the CSV. This guarantees consistent name matching.

    Args:
        pdb_dir: Directory containing PDB files.

    Returns:
        Dict mapping cleaned complex names to their PDB file paths.
    """
    from toolkit import parse_complex_name

    lookup: dict[str, Path] = {}
    for f in pdb_dir.iterdir():
        if f.is_file() and f.suffix == '.pdb':
            clean_name, _, _, _ = parse_complex_name(f.name)
            lookup[clean_name] = f
    return lookup


# ── Main Generation Function ────────────────────────────────────────

# Quality tier ordering for min_tier filtering
_TIER_ORDER = {'High': 3, 'Medium': 2, 'Low': 1}


def generate_pymol_scripts_for_results(
    results: list[dict],
    pdb_dir: str,
    output_dir: Optional[str] = None,
    min_tier: str = 'High',
    include_variants: bool = True,
    render_png: bool = False,
    verbose: bool = False,
) -> int:
    """Generate PyMOL .pml scripts for qualifying complexes.

    Main entry point from toolkit.py. Iterates results, filters by quality
    tier, re-reads PDBs for interface data, and writes one .pml file per
    qualifying complex.

    Args:
        results: List of per-complex result dicts from the pipeline.
        pdb_dir: Directory containing PDB files.
        output_dir: Output directory for .pml files. None uses
            ./pymol_scripts/ in the current working directory.
        min_tier: Minimum quality_tier_v2 for script generation.
        include_variants: If True, parse variant_details and add variant
            highlighting to scripts.
        render_png: If True, uncomment ray/png commands in generated scripts.
        verbose: Print progress to stderr.

    Returns:
        Number of .pml scripts generated.
    """
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), DEFAULT_PYMOL_OUTPUT_DIR)

    os.makedirs(output_dir, exist_ok=True)

    # Build PDB lookup using toolkit's name-cleaning logic (scan once)
    pdb_lookup = _build_pdb_lookup(Path(pdb_dir))
    if verbose:
        print(f"  [PyMOL] Found {len(pdb_lookup)} PDB files in {pdb_dir}",
              file=sys.stderr)

    min_tier_val = _TIER_ORDER.get(min_tier, 3)

    # Pre-count qualifying complexes for accurate progress bar total
    qualifying = [
        row for row in results
        if _TIER_ORDER.get(
            row.get('quality_tier_v2', row.get('quality_tier', 'Low')), 0
        ) >= min_tier_val
    ]

    n_generated = 0
    n_skipped = 0

    # Set up progress bar (tqdm if available, print fallback otherwise)
    use_bar = tqdm is not None and verbose
    if use_bar:
        pbar = tqdm(
            total=len(qualifying), desc="PyMOL scripts", unit="script",
            file=sys.stderr, ncols=100,
            bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} "
                       "[{elapsed}<{remaining}, {rate_fmt}]",
        )
    elif verbose:
        print(f"  [PyMOL] Generating scripts for {len(qualifying)} "
              f"qualifying complexes...", file=sys.stderr)

    for row in qualifying:
        complex_name = row.get('complex_name', '')

        # Locate PDB file via pre-built lookup
        pdb_path = pdb_lookup.get(complex_name)
        if pdb_path is None:
            if verbose and not use_bar:
                print(f"  [PyMOL] PDB not found for {complex_name}, skipping",
                      file=sys.stderr)
            n_skipped += 1
            if use_bar:
                pbar.update(1)
            continue

        # Extract interface data
        try:
            iface = extract_interface_data(pdb_path)
        except Exception as exc:
            if verbose and not use_bar:
                print(f"  [PyMOL] Error extracting interface for "
                      f"{complex_name}: {exc}", file=sys.stderr)
            n_skipped += 1
            if use_bar:
                pbar.update(1)
            continue

        # Parse variant details if available
        var_a = None
        var_b = None
        if include_variants:
            details_a = row.get('variant_details_a', '')
            details_b = row.get('variant_details_b', '')
            if details_a:
                var_a = parse_variant_details_for_pymol(details_a)
            if details_b:
                var_b = parse_variant_details_for_pymol(details_b)

        # Build PNG output path if rendering
        png_path = None
        if render_png:
            png_path = str(Path(output_dir) / f"{complex_name}.png")

        # Generate script
        script = build_pymol_script(
            pdb_path=str(pdb_path.resolve()),
            complex_name=complex_name,
            chain_a=iface['chain_a'],
            chain_b=iface['chain_b'],
            interface_resi_a=iface['interface_resi_a'],
            interface_resi_b=iface['interface_resi_b'],
            variant_records_a=var_a,
            variant_records_b=var_b,
            render_png=render_png,
            output_png_path=png_path,
        )

        # Write .pml file
        pml_path = Path(output_dir) / f"{complex_name}.pml"
        with open(pml_path, 'w', encoding='utf-8') as f:
            f.write(script)

        n_generated += 1

        if use_bar:
            pbar.update(1)
        elif verbose and n_generated % 100 == 0:
            print(f"  [PyMOL] {n_generated} scripts generated...",
                  file=sys.stderr)

    if use_bar:
        pbar.close()

    if verbose:
        print(f"  [PyMOL] Complete: {n_generated} scripts generated, "
              f"{n_skipped} skipped", file=sys.stderr)

    return n_generated


# ── py3Dmol Fallback ─────────────────────────────────────────────────

def generate_py3dmol_view(
    pdb_path: Union[str, Path],
    chain_a: str,
    chain_b: str,
    interface_resi_a: list[int],
    interface_resi_b: list[int],
    variant_records_a: Optional[list[dict]] = None,
    variant_records_b: Optional[list[dict]] = None,
    width: int = 800,
    height: int = 600,
):
    """Generate a py3Dmol interactive view for Jupyter notebook rendering.

    Mirrors the PyMOL script layers (chain colouring, interface highlighting,
    variant colouring) in an interactive 3D viewer.

    Args:
        pdb_path: Path to the PDB file.
        chain_a: First chain identifier.
        chain_b: Second chain identifier.
        interface_resi_a: PDB residue numbers at interface on chain A.
        interface_resi_b: PDB residue numbers at interface on chain B.
        variant_records_a: Parsed variant dicts for chain A. None to skip.
        variant_records_b: Parsed variant dicts for chain B. None to skip.
        width: Viewer width in pixels.
        height: Viewer height in pixels.

    Returns:
        py3Dmol.view object (call .show() to render), or None if py3Dmol
        is not installed.
    """
    if not _HAS_PY3DMOL:
        return None

    pdb_path = Path(pdb_path)
    with open(pdb_path, 'r', encoding='utf-8', errors='replace') as f:
        pdb_string = f.read()

    view = py3Dmol.view(width=width, height=height)
    view.addModel(pdb_string, 'pdb')

    # Chain colouring (cartoon)
    colour_a = CHAIN_COLOURS.get(chain_a, 'marine')
    colour_b = CHAIN_COLOURS.get(chain_b, 'salmon')
    view.setStyle({'chain': chain_a}, {'cartoon': {'color': colour_a}})
    view.setStyle({'chain': chain_b}, {'cartoon': {'color': colour_b}})

    # Interface highlighting (sticks)
    if interface_resi_a:
        view.addStyle(
            {'chain': chain_a, 'resi': interface_resi_a},
            {'stick': {'color': INTERFACE_COLOUR}},
        )
    if interface_resi_b:
        view.addStyle(
            {'chain': chain_b, 'resi': interface_resi_b},
            {'stick': {'color': INTERFACE_COLOUR}},
        )

    # Variant highlighting (spheres by context)
    for chain, records in [(chain_a, variant_records_a),
                           (chain_b, variant_records_b)]:
        if not records:
            continue
        for var in records:
            pos = var.get('position')
            ctx = var.get('context', 'unknown')
            colour = VARIANT_CONTEXT_COLOURS.get(ctx, VARIANT_DEFAULT_COLOUR)
            if pos is not None:
                view.addStyle(
                    {'chain': chain, 'resi': int(pos)},
                    {'sphere': {'color': colour, 'radius': 0.8}},
                )

    view.zoomTo()
    return view


# ── Standalone CLI ───────────────────────────────────────────────────

def _cli_generate(args) -> None:
    """Handle the 'generate' subcommand: single PDB -> .pml."""
    pdb_path = Path(args.pdb)
    if not pdb_path.exists():
        print(f"Error: PDB file not found: {pdb_path}", file=sys.stderr)
        sys.exit(1)

    complex_name = args.name or pdb_path.stem
    output_dir = args.output or '.'
    os.makedirs(output_dir, exist_ok=True)

    # Extract interface data
    print(f"Reading PDB: {pdb_path}", file=sys.stderr)
    iface = extract_interface_data(pdb_path)
    print(f"  Chain pair: {iface['chain_a']}-{iface['chain_b']}", file=sys.stderr)
    print(f"  Interface residues: {len(iface['interface_resi_a'])} (A) + "
          f"{len(iface['interface_resi_b'])} (B)", file=sys.stderr)

    png_path = None
    if args.render:
        png_path = str(Path(output_dir) / f"{complex_name}.png")

    script = build_pymol_script(
        pdb_path=str(pdb_path.resolve()),
        complex_name=complex_name,
        chain_a=iface['chain_a'],
        chain_b=iface['chain_b'],
        interface_resi_a=iface['interface_resi_a'],
        interface_resi_b=iface['interface_resi_b'],
        render_png=args.render,
        output_png_path=png_path,
    )

    pml_path = Path(output_dir) / f"{complex_name}.pml"
    with open(pml_path, 'w', encoding='utf-8') as f:
        f.write(script)

    print(f"Script written: {pml_path}", file=sys.stderr)
    if args.render:
        print(f"  Render with: pymol -c {pml_path}", file=sys.stderr)


def _cli_batch(args) -> None:
    """Handle the 'batch' subcommand: CSV + PDB dir -> .pml scripts."""
    csv_path = Path(args.csv)
    pdb_dir = Path(args.pdb_dir)

    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    if not pdb_dir.is_dir():
        print(f"Error: PDB directory not found: {pdb_dir}", file=sys.stderr)
        sys.exit(1)

    # Read results from CSV
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        results = list(reader)

    print(f"Loaded {len(results)} rows from {csv_path}", file=sys.stderr)

    output_dir = args.output or os.path.join(os.getcwd(), DEFAULT_PYMOL_OUTPUT_DIR)

    n_generated = generate_pymol_scripts_for_results(
        results,
        pdb_dir=str(pdb_dir),
        output_dir=output_dir,
        min_tier=args.min_tier,
        include_variants=not args.no_variants,
        render_png=args.render,
        verbose=True,
    )

    print(f"\n{n_generated} PyMOL scripts written to {output_dir}",
          file=sys.stderr)


def main() -> None:
    """CLI entry point for pymol_scripts.py."""
    parser = argparse.ArgumentParser(
        description="Generate PyMOL .pml scripts for AlphaFold2 complexes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest='command', required=True)

    # -- generate subcommand --
    p_gen = subparsers.add_parser(
        'generate',
        help="Generate a .pml script for a single PDB file.",
    )
    p_gen.add_argument('--pdb', required=True,
                       help="Path to the PDB file.")
    p_gen.add_argument('--output', default=None,
                       help="Output directory (default: current directory).")
    p_gen.add_argument('--render', action='store_true',
                       help="Include ray-tracing and PNG commands (uncommented).")
    p_gen.add_argument('--name', default=None,
                       help="Override the complex name (default: PDB filename stem).")
    p_gen.set_defaults(func=_cli_generate)

    # -- batch subcommand --
    p_batch = subparsers.add_parser(
        'batch',
        help="Generate .pml scripts for all qualifying complexes from a CSV.",
    )
    p_batch.add_argument('--csv', required=True,
                         help="Path to toolkit results CSV file.")
    p_batch.add_argument('--pdb-dir', required=True,
                         help="Directory containing PDB files.")
    p_batch.add_argument('--output', default=None,
                         help="Output directory for .pml files "
                              "(default: ./pymol_scripts/).")
    p_batch.add_argument('--min-tier', default='High',
                         choices=['High', 'Medium', 'Low'],
                         help="Minimum quality tier for script generation "
                              "(default: High).")
    p_batch.add_argument('--render', action='store_true',
                         help="Include ray-tracing and PNG commands (uncommented).")
    p_batch.add_argument('--no-variants', action='store_true',
                         help="Skip variant highlighting.")
    p_batch.set_defaults(func=_cli_batch)

    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
